name: build

on:
  pull_request:
    branches:
      - stable
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '**.txt'
      - '!CMakeLists.txt'
      - 'scripts/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: brew install cmake

      - name: Build project
        uses: threeal/cmake-action@v2.1.0
        with:
          cxx-compiler: clang++
