name: build

on:
  pull_request:
    branches:
      - stable
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '**.txt'
      - '!CMakeLists.txt'
      - 'scripts/**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            cxx: clang++
          - os: ubuntu-latest
            cxx: g++

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build project
        uses: threeal/cmake-action@v2.1.0
        with:
          cxx-compiler: ${{ matrix.cxx }}
