name: cppcheck

on:
  pull_request:
    branches:
      - stable
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '**.txt'
      - '!suppressions.txt'
      - 'scripts/**'
      - '!scripts/cppcheck.sh'

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up brew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install cppcheck
        run: brew install cppcheck

      - name: Run cppcheck
        run: ./scripts/cppcheck.sh
