name: cpplint

on:
  pull_request:
    branches:
      - stable
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '**.txt'
      - 'scripts/**'
      - '!scripts/cpplint.sh'

jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up brew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install cppcheck
        run: brew install cpplint

      - name: Run cpplint
        run: ./scripts/cpplint.sh
